### ISSUE TITLE
File with columns / logic to feed app components column lists and display names

### ISSUE THREAD

**Issue by mepearson** [mepearson/ecorise_dash#19]
A file with the requisite logic so the app can build things dynamically.  This is needed for the following:

- Dropdown lists for pie and bar charts (currently hard coded)
- List of columns to show in the organizations and programs tabs (currently hardcoded. This could also be done by limiting the data fields provided in the underlying dataset.)
- Display names for the columns in the tables of the organizations and programs tabs

**Comment by ajdabrowski** [comment]
Please see "dashboard-data-005" in the shared GDrive. I've created two files for you:

"dashboard_terms_dictionary.csv" contains much the same information as previously included within "filter_dict.csv". It will provide you with all the terms used by each field that's relevant for the dashboard and includes display names for the fields and terms. I've also added a numeric "term_order" to indicate the order in which terms should be presented on the interface for a particular field. 

"directory_fields_dictionary.csv" is for the "directory" component that displays "Organization Records" and "Program Records" as tables and allows users to download CSVs with the records that they've filtered down to within the dashboard. This file includes the fields (e.g. columns) that should be available for download, their order in the table ("column_order"), whether or not they should be diplayed within the web interface ("display"), and their display name.

I believe this should cover the most requirements in this issue. 

Which data fields should be used for filters, pie charts, bar charts, or sunbursts, seems to have been decided and adjusted in an ad hoc manner during the dashboard building. That information will need to be extracted from what you (or Je'aime) hard coded and documented so that I can add it into "dashboard_terms_dictionary.csv" or another appropriate place.

**Comment by ajdabrowski** [comment]
Separately, the fields in both "Organizations.csv" and "Programs.csv" have been reduced to include those that are used by the dashboard component, the "directory" component, or both. For details see "20210105-ecorise-data-transformations.pdf" within "dashboard-data-005" in the shared GDrive.

**Comment by ajdabrowski** [comment]
I've updated "dashboard_terms_dictionary.csv" in "dashboard-data-005" to include information requested for:

- Dropdown lists for pie and bar charts 

"dashboard_terms_dictionary.csv" now includes two Yes/No columns, "pie_chart" and "bar_chart" indicating which data fields and term should be included for building the pie chart and bar chart respectively.
